"""add ai generation cache table

Revision ID: 2bcbcb330485
Revises: 4f8887bceccb
Create Date: 2026-09-12 16:36:20.104631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.db.types import GUID

revision: str = '2bcbcb330485'
down_revision: Union[str, None] = '4f8887bceccb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_generation_cache',
    sa.Column('task', sa.String(length=64), nullable=False),
    sa.Column('prompt_version', sa.String(length=16), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('result_json', sa.Text(), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task', 'prompt_version', 'model', 'input_hash', name='uq_ai_cache_key')
    )
    op.create_index(op.f('ix_ai_generation_cache_task'), 'ai_generation_cache', ['task'], unique=False)
    op.create_foreign_key('fk_experiments_winning_variant_id', 'experiments', 'experiment_variants', ['winning_variant_id'], ['id'], ondelete='SET NULL', use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_experiments_winning_variant_id', 'experiments', type_='foreignkey')
    op.drop_index(op.f('ix_ai_generation_cache_task'), table_name='ai_generation_cache')
    op.drop_table('ai_generation_cache')
    # ### end Alembic commands ###
