"""initial schema

Revision ID: 4f8887bceccb
Revises: 
Create Date: 2026-09-12 15:33:23.546023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.db.types import GUID

revision: str = '4f8887bceccb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'EDITOR', 'ANALYST', 'VIEWER', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('channels',
    sa.Column('owner_user_id', GUID(), nullable=False),
    sa.Column('youtube_channel_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=1000), nullable=True),
    sa.Column('country', sa.String(length=8), nullable=True),
    sa.Column('subscriber_count', sa.BigInteger(), nullable=True),
    sa.Column('view_count', sa.BigInteger(), nullable=True),
    sa.Column('video_count', sa.BigInteger(), nullable=True),
    sa.Column('oauth_access_token_encrypted', sa.Text(), nullable=True),
    sa.Column('oauth_refresh_token_encrypted', sa.Text(), nullable=True),
    sa.Column('oauth_token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_status', sa.Enum('NEVER_SYNCED', 'PENDING', 'SYNCING', 'SUCCEEDED', 'FAILED', name='channel_sync_status'), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sync_error', sa.Text(), nullable=True),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('youtube_channel_id')
    )
    op.create_index(op.f('ix_channels_owner_user_id'), 'channels', ['owner_user_id'], unique=False)
    op.create_table('competitors',
    sa.Column('owner_user_id', GUID(), nullable=False),
    sa.Column('youtube_channel_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=1000), nullable=True),
    sa.Column('subscriber_count', sa.BigInteger(), nullable=True),
    sa.Column('view_count', sa.BigInteger(), nullable=True),
    sa.Column('video_count', sa.BigInteger(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competitors_owner_user_id'), 'competitors', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_competitors_youtube_channel_id'), 'competitors', ['youtube_channel_id'], unique=False)
    op.create_table('jobs',
    sa.Column('job_type', sa.String(length=64), nullable=False),
    sa.Column('owner_user_id', GUID(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=200), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', 'RETRYING', 'DEAD_LETTER', name='job_status'), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('args_json', sa.Text(), nullable=True),
    sa.Column('result_json', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_jobs_job_type'), 'jobs', ['job_type'], unique=False)
    op.create_index(op.f('ix_jobs_owner_user_id'), 'jobs', ['owner_user_id'], unique=False)
    op.create_table('kill_switches',
    sa.Column('owner_user_id', GUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_user_id')
    )
    op.create_table('notifications',
    sa.Column('user_id', GUID(), nullable=False),
    sa.Column('event', sa.Enum('NEW_OPPORTUNITY', 'PERFORMANCE_ANOMALY', 'COMPETITOR_SPIKE', 'SYNC_FAILURE', 'WEEKLY_REPORT', 'RECOMMENDATION_READY', 'GROWTH_ACTIONS_READY', 'PUBLISHING_RESULT', name='notification_event'), nullable=False),
    sa.Column('channel', sa.Enum('IN_APP', 'EMAIL', 'TELEGRAM', name='notification_channel'), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivery_error', sa.Text(), nullable=True),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('sessions',
    sa.Column('user_id', GUID(), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=128), nullable=False),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('refresh_token_hash')
    )
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('trends',
    sa.Column('owner_user_id', GUID(), nullable=False),
    sa.Column('keyword', sa.String(length=300), nullable=False),
    sa.Column('source', sa.Enum('YOUTUBE_SIGNAL', 'CREATOR_HISTORY', 'COMPETITOR_MOMENTUM', 'GOOGLE_TRENDS', 'RSS_NEWS', name='trend_source'), nullable=False),
    sa.Column('trend_score', sa.Float(), nullable=True),
    sa.Column('growth_score', sa.Float(), nullable=True),
    sa.Column('competition_score', sa.Float(), nullable=True),
    sa.Column('audience_fit_score', sa.Float(), nullable=True),
    sa.Column('creator_fit_score', sa.Float(), nullable=True),
    sa.Column('timeliness_score', sa.Float(), nullable=True),
    sa.Column('content_gap_score', sa.Float(), nullable=True),
    sa.Column('opportunity_score', sa.Float(), nullable=True),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trends_keyword'), 'trends', ['keyword'], unique=False)
    op.create_index(op.f('ix_trends_owner_user_id'), 'trends', ['owner_user_id'], unique=False)
    op.create_table('analytics_snapshots',
    sa.Column('channel_id', GUID(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_views', sa.Integer(), nullable=True),
    sa.Column('total_subscribers', sa.Integer(), nullable=True),
    sa.Column('average_views_per_video', sa.Float(), nullable=True),
    sa.Column('median_views_per_video', sa.Float(), nullable=True),
    sa.Column('upload_frequency_per_week', sa.Float(), nullable=True),
    sa.Column('engagement_rate', sa.Float(), nullable=True),
    sa.Column('performance_score', sa.Float(), nullable=True),
    sa.Column('engagement_score', sa.Float(), nullable=True),
    sa.Column('retention_score', sa.Float(), nullable=True),
    sa.Column('subscriber_conversion_score', sa.Float(), nullable=True),
    sa.Column('data_quality', sa.String(length=24), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_snapshots_captured_at'), 'analytics_snapshots', ['captured_at'], unique=False)
    op.create_index(op.f('ix_analytics_snapshots_channel_id'), 'analytics_snapshots', ['channel_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', GUID(), nullable=True),
    sa.Column('channel_id', GUID(), nullable=True),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('content_id', sa.String(length=200), nullable=True),
    sa.Column('campaign_id', GUID(), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('authorization_state', sa.String(length=50), nullable=True),
    sa.Column('rule_set_json', sa.Text(), nullable=True),
    sa.Column('result', sa.String(length=32), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('before_state_json', sa.Text(), nullable=True),
    sa.Column('after_state_json', sa.Text(), nullable=True),
    sa.Column('id', GUID(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action_type'), 'audit_logs', ['action_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('competitor_videos',
    sa.Column('competitor_id', GUID(), nullable=False),
    sa.Column('youtube_video_id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=1000), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('view_count', sa.BigInteger(), nullable=True),
    sa.Column('like_count', sa.BigInteger(), nullable=True),
    sa.Column('comment_count', sa.BigInteger(), nullable=True),
    sa.Column('category_id', sa.String(length=16), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('youtube_video_id')
    )
    op.create_index(op.f('ix_competitor_videos_competitor_id'), 'competitor_videos', ['competitor_id'], unique=False)
    op.create_table('growth_actions',
    sa.Column('owner_user_id', GUID(), nullable=False),
    sa.Column('channel_id', GUID(), nullable=True),
    sa.Column('run_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('expected_objective', sa.String(length=200), nullable=True),
    sa.Column('confidence', sa.String(length=24), nullable=False),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('execution_status', sa.String(length=32), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_growth_actions_owner_user_id'), 'growth_actions', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_growth_actions_run_date'), 'growth_actions', ['run_date'], unique=False)
    op.create_table('growth_scores',
    sa.Column('channel_id', GUID(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('content_score', sa.Float(), nullable=True),
    sa.Column('discovery_score', sa.Float(), nullable=True),
    sa.Column('ctr_score', sa.Float(), nullable=True),
    sa.Column('retention_score', sa.Float(), nullable=True),
    sa.Column('subscriber_conversion_score', sa.Float(), nullable=True),
    sa.Column('returning_viewers_score', sa.Float(), nullable=True),
    sa.Column('distribution_score', sa.Float(), nullable=True),
    sa.Column('consistency_score', sa.Float(), nullable=True),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_growth_scores_channel_id'), 'growth_scores', ['channel_id'], unique=False)
    op.create_table('publishing_rules',
    sa.Column('owner_user_id', GUID(), nullable=False),
    sa.Column('channel_id', GUID(), nullable=False),
    sa.Column('mode', sa.Enum('ASSIST', 'AUTO_PREPARE', 'AUTHORIZED_AUTONOMOUS', name='publishing_mode'), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('max_videos_per_day', sa.Integer(), nullable=False),
    sa.Column('allowed_categories_json', sa.Text(), nullable=True),
    sa.Column('minimum_content_score', sa.Float(), nullable=False),
    sa.Column('minimum_subscriber_score', sa.Float(), nullable=False),
    sa.Column('allowed_publish_windows_json', sa.Text(), nullable=True),
    sa.Column('allowed_platforms_json', sa.Text(), nullable=True),
    sa.Column('require_thumbnail', sa.Boolean(), nullable=False),
    sa.Column('require_metadata_validation', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publishing_rules_channel_id'), 'publishing_rules', ['channel_id'], unique=False)
    op.create_index(op.f('ix_publishing_rules_owner_user_id'), 'publishing_rules', ['owner_user_id'], unique=False)
    op.create_table('subscriber_growth_metrics',
    sa.Column('channel_id', GUID(), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('dimension', sa.String(length=32), nullable=False),
    sa.Column('dimension_key', sa.String(length=200), nullable=True),
    sa.Column('subscriber_growth_rate', sa.Float(), nullable=True),
    sa.Column('subscriber_conversion_rate', sa.Float(), nullable=True),
    sa.Column('subscribers_per_1000_views', sa.Float(), nullable=True),
    sa.Column('returning_viewer_rate', sa.Float(), nullable=True),
    sa.Column('data_quality', sa.String(length=24), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriber_growth_metrics_channel_id'), 'subscriber_growth_metrics', ['channel_id'], unique=False)
    op.create_table('topics',
    sa.Column('owner_user_id', GUID(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('trend_id', GUID(), nullable=True),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trend_id'], ['trends.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topics_owner_user_id'), 'topics', ['owner_user_id'], unique=False)
    op.create_table('videos',
    sa.Column('channel_id', GUID(), nullable=False),
    sa.Column('youtube_video_id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=1000), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.String(length=16), nullable=True),
    sa.Column('format', sa.Enum('SHORT', 'LONG_FORM', name='video_format'), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('view_count', sa.BigInteger(), nullable=True),
    sa.Column('like_count', sa.BigInteger(), nullable=True),
    sa.Column('comment_count', sa.BigInteger(), nullable=True),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('youtube_video_id')
    )
    op.create_index(op.f('ix_videos_channel_id'), 'videos', ['channel_id'], unique=False)
    op.create_table('distribution_campaigns',
    sa.Column('owner_user_id', GUID(), nullable=False),
    sa.Column('source_video_id', GUID(), nullable=True),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'READY', 'SCHEDULED', 'RUNNING', 'COMPLETED', 'ANALYZING', name='campaign_status'), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_video_id'], ['videos.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_distribution_campaigns_owner_user_id'), 'distribution_campaigns', ['owner_user_id'], unique=False)
    op.create_table('experiments',
    sa.Column('owner_user_id', GUID(), nullable=False),
    sa.Column('video_id', GUID(), nullable=True),
    sa.Column('experiment_type', sa.String(length=50), nullable=False),
    sa.Column('hypothesis', sa.Text(), nullable=False),
    sa.Column('metric', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'RUNNING', 'COMPLETED', 'INSUFFICIENT_DATA', name='experiment_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('minimum_sample_size', sa.Integer(), nullable=False),
    sa.Column('winning_variant_id', GUID(), nullable=True),
    sa.Column('confidence', sa.String(length=24), nullable=True),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['winning_variant_id'], ['experiment_variants.id'], name='fk_experiments_winning_variant_id', ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_experiments_owner_user_id'), 'experiments', ['owner_user_id'], unique=False)
    op.create_table('hooks',
    sa.Column('owner_user_id', GUID(), nullable=False),
    sa.Column('topic_id', GUID(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('category', sa.Enum('CURIOSITY', 'PROBLEM', 'CONTRARIAN', 'DATA_DRIVEN', 'STORY', 'QUESTION', 'URGENCY', 'TRANSFORMATION', name='hook_category'), nullable=False),
    sa.Column('hook_score', sa.Float(), nullable=True),
    sa.Column('clarity_score', sa.Float(), nullable=True),
    sa.Column('curiosity_score', sa.Float(), nullable=True),
    sa.Column('specificity_score', sa.Float(), nullable=True),
    sa.Column('audience_fit_score', sa.Float(), nullable=True),
    sa.Column('generated_by', sa.String(length=32), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hooks_owner_user_id'), 'hooks', ['owner_user_id'], unique=False)
    op.create_table('opportunities',
    sa.Column('topic_id', GUID(), nullable=False),
    sa.Column('audience_demand_score', sa.Float(), nullable=True),
    sa.Column('momentum_score', sa.Float(), nullable=True),
    sa.Column('competition_score', sa.Float(), nullable=True),
    sa.Column('creator_fit_score', sa.Float(), nullable=True),
    sa.Column('historical_performance_score', sa.Float(), nullable=True),
    sa.Column('content_gap_score', sa.Float(), nullable=True),
    sa.Column('freshness_score', sa.Float(), nullable=True),
    sa.Column('level', sa.Enum('HIGH', 'MEDIUM', 'LOW', 'INSUFFICIENT_DATA', name='opportunity_level'), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opportunities_topic_id'), 'opportunities', ['topic_id'], unique=False)
    op.create_table('recommendations',
    sa.Column('owner_user_id', GUID(), nullable=False),
    sa.Column('topic_id', GUID(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(length=300), nullable=False),
    sa.Column('format', sa.String(length=50), nullable=False),
    sa.Column('target_audience', sa.String(length=300), nullable=True),
    sa.Column('content_angle', sa.Text(), nullable=True),
    sa.Column('hook', sa.Text(), nullable=True),
    sa.Column('title_candidates_json', sa.Text(), nullable=True),
    sa.Column('thumbnail_concept', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('supporting_evidence', sa.Text(), nullable=True),
    sa.Column('opportunity_score', sa.Float(), nullable=True),
    sa.Column('viral_potential_score', sa.Float(), nullable=True),
    sa.Column('discovery_score', sa.Float(), nullable=True),
    sa.Column('subscriber_potential_score', sa.Float(), nullable=True),
    sa.Column('retention_potential_score', sa.Float(), nullable=True),
    sa.Column('audience_fit_score', sa.Float(), nullable=True),
    sa.Column('confidence', sa.String(length=24), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_owner_user_id'), 'recommendations', ['owner_user_id'], unique=False)
    op.create_table('research_projects',
    sa.Column('owner_user_id', GUID(), nullable=False),
    sa.Column('topic_id', GUID(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_projects_owner_user_id'), 'research_projects', ['owner_user_id'], unique=False)
    op.create_table('retention_metrics',
    sa.Column('video_id', GUID(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('early_dropoff_pct', sa.Float(), nullable=True),
    sa.Column('mid_video_dropoff_pct', sa.Float(), nullable=True),
    sa.Column('ending_dropoff_pct', sa.Float(), nullable=True),
    sa.Column('hook_failure_detected', sa.Boolean(), nullable=True),
    sa.Column('strong_segment_notes', sa.Text(), nullable=True),
    sa.Column('data_quality', sa.String(length=24), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('insight', sa.Text(), nullable=True),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_retention_metrics_video_id'), 'retention_metrics', ['video_id'], unique=False)
    op.create_table('scripts',
    sa.Column('owner_user_id', GUID(), nullable=False),
    sa.Column('topic_id', GUID(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('format', sa.Enum('SHORT', 'FIVE_MIN', 'TEN_MIN', 'FIFTEEN_MIN', 'LONG_FORM', name='script_format'), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scripts_owner_user_id'), 'scripts', ['owner_user_id'], unique=False)
    op.create_table('seo_records',
    sa.Column('owner_user_id', GUID(), nullable=False),
    sa.Column('video_id', GUID(), nullable=True),
    sa.Column('title_suggestions', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('keywords', sa.Text(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('chapters', sa.Text(), nullable=True),
    sa.Column('hashtags', sa.Text(), nullable=True),
    sa.Column('search_intent', sa.String(length=200), nullable=True),
    sa.Column('topic_clusters', sa.Text(), nullable=True),
    sa.Column('generated_by', sa.String(length=32), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seo_records_owner_user_id'), 'seo_records', ['owner_user_id'], unique=False)
    op.create_table('thumbnail_briefs',
    sa.Column('owner_user_id', GUID(), nullable=False),
    sa.Column('video_id', GUID(), nullable=True),
    sa.Column('topic_id', GUID(), nullable=True),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('emotion', sa.String(length=100), nullable=True),
    sa.Column('text_overlay', sa.String(length=60), nullable=True),
    sa.Column('text_overlay_length', sa.Integer(), nullable=True),
    sa.Column('visual_hierarchy_notes', sa.Text(), nullable=True),
    sa.Column('contrast_notes', sa.Text(), nullable=True),
    sa.Column('curiosity_notes', sa.Text(), nullable=True),
    sa.Column('brand_consistency_notes', sa.Text(), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('image_provider', sa.String(length=64), nullable=True),
    sa.Column('image_path', sa.String(length=1000), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_thumbnail_briefs_owner_user_id'), 'thumbnail_briefs', ['owner_user_id'], unique=False)
    op.create_table('titles',
    sa.Column('owner_user_id', GUID(), nullable=False),
    sa.Column('topic_id', GUID(), nullable=True),
    sa.Column('video_id', GUID(), nullable=True),
    sa.Column('text', sa.String(length=200), nullable=False),
    sa.Column('ctr_potential_score', sa.Float(), nullable=True),
    sa.Column('clarity_score', sa.Float(), nullable=True),
    sa.Column('specificity_score', sa.Float(), nullable=True),
    sa.Column('curiosity_score', sa.Float(), nullable=True),
    sa.Column('search_relevance_score', sa.Float(), nullable=True),
    sa.Column('audience_fit_score', sa.Float(), nullable=True),
    sa.Column('is_experiment_variant', sa.Boolean(), nullable=False),
    sa.Column('generated_by', sa.String(length=32), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_titles_owner_user_id'), 'titles', ['owner_user_id'], unique=False)
    op.create_table('video_metrics',
    sa.Column('video_id', GUID(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('view_count', sa.BigInteger(), nullable=True),
    sa.Column('like_count', sa.BigInteger(), nullable=True),
    sa.Column('comment_count', sa.BigInteger(), nullable=True),
    sa.Column('average_view_duration_seconds', sa.Float(), nullable=True),
    sa.Column('average_view_percentage', sa.Float(), nullable=True),
    sa.Column('estimated_ctr', sa.Float(), nullable=True),
    sa.Column('subscribers_gained', sa.Integer(), nullable=True),
    sa.Column('traffic_source_breakdown_json', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_metrics_captured_at'), 'video_metrics', ['captured_at'], unique=False)
    op.create_index(op.f('ix_video_metrics_video_id'), 'video_metrics', ['video_id'], unique=False)
    op.create_table('content_items',
    sa.Column('owner_user_id', GUID(), nullable=False),
    sa.Column('assignee_user_id', GUID(), nullable=True),
    sa.Column('topic_id', GUID(), nullable=True),
    sa.Column('video_id', GUID(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('status', sa.Enum('IDEA', 'RESEARCH', 'OUTLINE', 'SCRIPT', 'RECORDING', 'EDITING', 'THUMBNAIL', 'SEO', 'READY', 'PUBLISHED', 'ANALYZING', name='content_status'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('checklist_json', sa.Text(), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_publish_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('is_short', sa.Boolean(), nullable=False),
    sa.Column('recurring_format', sa.String(length=100), nullable=True),
    sa.Column('campaign_id', GUID(), nullable=True),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assignee_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['campaign_id'], ['distribution_campaigns.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_items_owner_user_id'), 'content_items', ['owner_user_id'], unique=False)
    op.create_table('distribution_assets',
    sa.Column('campaign_id', GUID(), nullable=False),
    sa.Column('source_video_id', GUID(), nullable=True),
    sa.Column('source_segment', sa.String(length=200), nullable=True),
    sa.Column('platform', sa.Enum('YOUTUBE', 'INSTAGRAM', 'FACEBOOK', 'X', 'LINKEDIN', name='distribution_platform'), nullable=False),
    sa.Column('format', sa.String(length=50), nullable=False),
    sa.Column('hook', sa.Text(), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('cta', sa.Text(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'READY', 'SCHEDULED', 'PUBLISHED', 'FAILED', name='distribution_asset_status'), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('platform_post_id', sa.String(length=200), nullable=True),
    sa.Column('publication_status', sa.String(length=50), nullable=True),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['distribution_campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_video_id'], ['videos.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_distribution_assets_campaign_id'), 'distribution_assets', ['campaign_id'], unique=False)
    op.create_table('experiment_variants',
    sa.Column('experiment_id', GUID(), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=True),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_experiment_variants_experiment_id'), 'experiment_variants', ['experiment_id'], unique=False)
    op.create_table('research_sources',
    sa.Column('research_project_id', GUID(), nullable=False),
    sa.Column('url', sa.String(length=2000), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('claim', sa.Text(), nullable=True),
    sa.Column('citation', sa.Text(), nullable=True),
    sa.Column('credibility', sa.Enum('VERIFIED', 'UNVERIFIED', 'NEEDS_REVIEW', name='source_credibility'), nullable=False),
    sa.Column('added_by_ai', sa.Boolean(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['research_project_id'], ['research_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_sources_research_project_id'), 'research_sources', ['research_project_id'], unique=False)
    op.create_table('script_versions',
    sa.Column('script_id', GUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('hook', sa.Text(), nullable=True),
    sa.Column('setup', sa.Text(), nullable=True),
    sa.Column('promise', sa.Text(), nullable=True),
    sa.Column('main_points', sa.Text(), nullable=True),
    sa.Column('examples', sa.Text(), nullable=True),
    sa.Column('transitions', sa.Text(), nullable=True),
    sa.Column('pattern_interrupts', sa.Text(), nullable=True),
    sa.Column('cta', sa.Text(), nullable=True),
    sa.Column('ending', sa.Text(), nullable=True),
    sa.Column('full_text', sa.Text(), nullable=True),
    sa.Column('generated_by', sa.String(length=32), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['script_id'], ['scripts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_script_versions_script_id'), 'script_versions', ['script_id'], unique=False)
    op.create_table('content_events',
    sa.Column('content_item_id', GUID(), nullable=False),
    sa.Column('actor_user_id', GUID(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('from_status', sa.Enum('IDEA', 'RESEARCH', 'OUTLINE', 'SCRIPT', 'RECORDING', 'EDITING', 'THUMBNAIL', 'SEO', 'READY', 'PUBLISHED', 'ANALYZING', name='content_status'), nullable=True),
    sa.Column('to_status', sa.Enum('IDEA', 'RESEARCH', 'OUTLINE', 'SCRIPT', 'RECORDING', 'EDITING', 'THUMBNAIL', 'SEO', 'READY', 'PUBLISHED', 'ANALYZING', name='content_status'), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['content_item_id'], ['content_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_events_content_item_id'), 'content_events', ['content_item_id'], unique=False)
    op.create_table('publishing_runs',
    sa.Column('owner_user_id', GUID(), nullable=False),
    sa.Column('channel_id', GUID(), nullable=False),
    sa.Column('content_item_id', GUID(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=200), nullable=False),
    sa.Column('mode', sa.Enum('ASSIST', 'AUTO_PREPARE', 'AUTHORIZED_AUTONOMOUS', name='publishing_mode'), nullable=False),
    sa.Column('state', sa.Enum('DRAFT', 'READY', 'VALIDATING', 'UPLOAD_QUEUED', 'UPLOADING', 'PROCESSING', 'SCHEDULED', 'PUBLISHED', 'FAILED', 'RETRY_PENDING', 'CANCELLED', name='publishing_state'), nullable=False),
    sa.Column('youtube_video_id', sa.String(length=32), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('approved_by_user_id', GUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['content_item_id'], ['content_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_publishing_runs_channel_id'), 'publishing_runs', ['channel_id'], unique=False)
    op.create_index(op.f('ix_publishing_runs_owner_user_id'), 'publishing_runs', ['owner_user_id'], unique=False)
    op.create_table('publishing_attempts',
    sa.Column('publishing_run_id', GUID(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('gate_passed', sa.Boolean(), nullable=False),
    sa.Column('gate_checks_json', sa.Text(), nullable=False),
    sa.Column('result', sa.String(length=32), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['publishing_run_id'], ['publishing_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publishing_attempts_publishing_run_id'), 'publishing_attempts', ['publishing_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_publishing_attempts_publishing_run_id'), table_name='publishing_attempts')
    op.drop_table('publishing_attempts')
    op.drop_index(op.f('ix_publishing_runs_owner_user_id'), table_name='publishing_runs')
    op.drop_index(op.f('ix_publishing_runs_channel_id'), table_name='publishing_runs')
    op.drop_table('publishing_runs')
    op.drop_index(op.f('ix_content_events_content_item_id'), table_name='content_events')
    op.drop_table('content_events')
    op.drop_index(op.f('ix_script_versions_script_id'), table_name='script_versions')
    op.drop_table('script_versions')
    op.drop_index(op.f('ix_research_sources_research_project_id'), table_name='research_sources')
    op.drop_table('research_sources')
    op.drop_index(op.f('ix_experiment_variants_experiment_id'), table_name='experiment_variants')
    op.drop_table('experiment_variants')
    op.drop_index(op.f('ix_distribution_assets_campaign_id'), table_name='distribution_assets')
    op.drop_table('distribution_assets')
    op.drop_index(op.f('ix_content_items_owner_user_id'), table_name='content_items')
    op.drop_table('content_items')
    op.drop_index(op.f('ix_video_metrics_video_id'), table_name='video_metrics')
    op.drop_index(op.f('ix_video_metrics_captured_at'), table_name='video_metrics')
    op.drop_table('video_metrics')
    op.drop_index(op.f('ix_titles_owner_user_id'), table_name='titles')
    op.drop_table('titles')
    op.drop_index(op.f('ix_thumbnail_briefs_owner_user_id'), table_name='thumbnail_briefs')
    op.drop_table('thumbnail_briefs')
    op.drop_index(op.f('ix_seo_records_owner_user_id'), table_name='seo_records')
    op.drop_table('seo_records')
    op.drop_index(op.f('ix_scripts_owner_user_id'), table_name='scripts')
    op.drop_table('scripts')
    op.drop_index(op.f('ix_retention_metrics_video_id'), table_name='retention_metrics')
    op.drop_table('retention_metrics')
    op.drop_index(op.f('ix_research_projects_owner_user_id'), table_name='research_projects')
    op.drop_table('research_projects')
    op.drop_index(op.f('ix_recommendations_owner_user_id'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_opportunities_topic_id'), table_name='opportunities')
    op.drop_table('opportunities')
    op.drop_index(op.f('ix_hooks_owner_user_id'), table_name='hooks')
    op.drop_table('hooks')
    op.drop_index(op.f('ix_experiments_owner_user_id'), table_name='experiments')
    op.drop_table('experiments')
    op.drop_index(op.f('ix_distribution_campaigns_owner_user_id'), table_name='distribution_campaigns')
    op.drop_table('distribution_campaigns')
    op.drop_index(op.f('ix_videos_channel_id'), table_name='videos')
    op.drop_table('videos')
    op.drop_index(op.f('ix_topics_owner_user_id'), table_name='topics')
    op.drop_table('topics')
    op.drop_index(op.f('ix_subscriber_growth_metrics_channel_id'), table_name='subscriber_growth_metrics')
    op.drop_table('subscriber_growth_metrics')
    op.drop_index(op.f('ix_publishing_rules_owner_user_id'), table_name='publishing_rules')
    op.drop_index(op.f('ix_publishing_rules_channel_id'), table_name='publishing_rules')
    op.drop_table('publishing_rules')
    op.drop_index(op.f('ix_growth_scores_channel_id'), table_name='growth_scores')
    op.drop_table('growth_scores')
    op.drop_index(op.f('ix_growth_actions_run_date'), table_name='growth_actions')
    op.drop_index(op.f('ix_growth_actions_owner_user_id'), table_name='growth_actions')
    op.drop_table('growth_actions')
    op.drop_index(op.f('ix_competitor_videos_competitor_id'), table_name='competitor_videos')
    op.drop_table('competitor_videos')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action_type'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_analytics_snapshots_channel_id'), table_name='analytics_snapshots')
    op.drop_index(op.f('ix_analytics_snapshots_captured_at'), table_name='analytics_snapshots')
    op.drop_table('analytics_snapshots')
    op.drop_index(op.f('ix_trends_owner_user_id'), table_name='trends')
    op.drop_index(op.f('ix_trends_keyword'), table_name='trends')
    op.drop_table('trends')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('kill_switches')
    op.drop_index(op.f('ix_jobs_owner_user_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_job_type'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_competitors_youtube_channel_id'), table_name='competitors')
    op.drop_index(op.f('ix_competitors_owner_user_id'), table_name='competitors')
    op.drop_table('competitors')
    op.drop_index(op.f('ix_channels_owner_user_id'), table_name='channels')
    op.drop_table('channels')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###

    # Alembic's autogenerate does not track ENUM type lifecycle across
    # drop_table (a type could in principle be shared by several tables), so
    # it never emits DROP TYPE here. Without this, re-running `upgrade head`
    # after a `downgrade base` fails with "type already exists".
    enum_type_names = [
        "user_role", "channel_sync_status", "job_status", "notification_event",
        "notification_channel", "trend_source", "publishing_mode", "video_format",
        "campaign_status", "experiment_status", "hook_category", "opportunity_level",
        "script_format", "content_status", "distribution_platform",
        "distribution_asset_status", "source_credibility", "publishing_state",
    ]
    bind = op.get_bind()
    for type_name in enum_type_names:
        sa.Enum(name=type_name).drop(bind, checkfirst=True)
